# Transformasi
## Data Australia Open 2013

In [17]:
import pandas as pd
import numpy as np
data=pd.read_csv("Australia Open 2013.csv", sep=";")
np.sum(data.isnull())

FSP     0
DBF     1
WNR     0
NPW    22
TPW     0
dtype: int64

In [18]:
data['DBF']=data['DBF'].fillna((data['DBF'].mean()))
data['NPW']=data['NPW'].fillna((data['NPW'].mean()))
np.sum(data.isnull())

FSP    0
DBF    0
WNR    0
NPW    0
TPW    0
dtype: int64

In [19]:
data.to_csv('Australia Open 2013_1.csv', sep=';')

In [20]:
from scipy.stats import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data2 = data[(z<3).all(axis=1)]
print(data2.shape)

[[4.57513782e-02 1.06759312e+00 8.66691697e-01 1.07162896e+00
  1.25520129e+00]
 [4.57513782e-02 1.06759312e+00 1.07263824e+00 3.34415413e-16
  9.57469057e-01]
 [1.31116755e+00 1.09824173e-01 1.63041012e-01 5.79258896e-02
  1.83365249e-01]
 [1.17056575e+00 5.28688459e-01 1.33007142e+00 3.34415413e-16
  2.42911696e-01]
 [2.06327557e+00 1.09824173e-01 9.18178332e-01 8.83369816e-01
  4.71645666e-01]
 [5.16655807e-01 4.29080489e-01 6.00677414e-02 9.77499386e-01
  1.23818802e-01]
 [9.38461197e-01 4.29080489e-01 3.68987554e-01 7.16832883e-01
  1.81144072e+00]
 [2.01417653e+00 1.09824173e-01 6.60745155e-01 1.25988810e+00
  1.01701550e+00]
 [3.76054011e-01 0.00000000e+00 7.12231791e-01 7.89240245e-01
  1.34452096e+00]
 [2.20387736e+00 1.09824173e-01 1.43304469e+00 3.34415413e-16
  1.48393526e+00]
 [1.17056575e+00 8.47944775e-01 6.77907367e-01 9.99221595e-01
  4.12099219e-01]
 [6.08158564e-01 1.38684944e+00 8.32367273e-01 3.18592393e-01
  1.93053361e+00]
 [5.16655807e-01 1.09824173e-01 6.00677414e-02 1.94051730e+00
  1.13610840e+00]
 [3.76054011e-01 1.09824173e-01 7.80880638e-01 2.22290601e+00
  7.39604676e-01]
 [1.86353175e-01 7.48336804e-01 1.53601796e+00 3.34415413e-16
  1.15642980e+00]
 [2.35452215e-01 1.06759312e+00 5.57771884e-01 7.89240245e-01
  1.73157287e+00]
 [9.38461197e-01 1.09824173e-01 6.09258520e-01 1.30333252e-01
  1.10633517e+00]
 [1.17056575e+00 2.44422635e+00 6.60745155e-01 3.34415413e-16
  5.01418889e-01]
 [1.59237114e+00 4.29080489e-01 3.00338707e-01 8.10962454e-01
  6.29963600e-01]
 [6.57257604e-01 7.48336804e-01 1.45878800e-01 8.83369816e-01
  5.40643930e-01]
 [1.86353175e-01 1.16720109e+00 3.17500919e-01 5.28573742e-01
  8.28924347e-01]
 [4.57513782e-02 4.29080489e-01 1.63899123e+00 3.34415413e-16
  1.04678873e+00]
 [4.67556767e-01 1.06759312e+00 4.54798613e-01 7.89240245e-01
  3.32231366e-01]
 [1.07906299e+00 7.48336804e-01 1.17561151e+00 1.35401767e+00
  5.10870706e-01]
 [4.67556767e-01 4.29080489e-01 7.63718426e-01 1.63640638e+00
  1.40406741e+00]
 [6.08158564e-01 1.09824173e-01 1.27858478e+00 3.34415413e-16
  1.12665658e+00]
 [8.89362157e-01 4.29080489e-01 7.12231791e-01 3.34415413e-16
  1.06711013e+00]
 [2.35452215e-01 1.48645741e+00 6.60745155e-01 3.34415413e-16
  1.24574947e+00]
 [6.57257604e-01 1.06759312e+00 7.29394002e-01 2.59942429e+00
  5.70417153e-01]
 [1.64147018e+00 5.28688459e-01 1.63899123e+00 3.34415413e-16
  1.70179964e+00]
 [1.86353175e-01 2.09432143e-01 4.29055296e-02 1.18748074e+00
  3.82325996e-01]
 [6.57257604e-01 1.38684944e+00 6.00677414e-02 5.79258896e-02
  4.51324259e-01]
 [1.31116755e+00 4.29080489e-01 8.58110591e-03 1.09335117e+00
  1.13610840e+00]
 [1.45176934e+00 2.12497004e+00 8.83853909e-01 9.05092025e-01
  2.42911696e-01]
 [4.67556767e-01 1.09824173e-01 1.48453132e+00 3.34415413e-16
  6.20511783e-01]
 [4.57513782e-02 5.28688459e-01 5.23447461e-01 1.07162896e+00
  3.82325996e-01]
 [2.35452215e-01 1.09824173e-01 3.97305204e+00 2.03464687e+00
  3.53828768e+00]
 [4.67556767e-01 1.09824173e-01 1.50169353e+00 8.10962454e-01
  9.77790464e-01]
 [1.17056575e+00 5.28688459e-01 4.29055296e-02 3.62036810e-02
  4.21551036e-01]
 [9.48504182e-02 1.06759312e+00 1.11554377e-01 6.95110675e-01
  2.42911696e-01]
 [1.02996395e+00 7.48336804e-01 3.51825342e-01 1.82466552e+00
  1.22542807e+00]
 [9.38461197e-01 1.16720109e+00 1.43304469e+00 3.34415413e-16
  1.23818802e-01]
 [1.07906299e+00 1.38684944e+00 9.69664968e-01 3.34415413e-16
  2.42911696e-01]
 [2.15477832e+00 7.48336804e-01 6.09258520e-01 9.77499386e-01
  2.42911696e-01]
 [1.31116755e+00 1.06759312e+00 1.43304469e+00 3.34415413e-16
  6.89510047e-01]
 [2.35452215e-01 5.28688459e-01 1.27858478e+00 3.34415413e-16
  5.10870706e-01]
 [6.08158564e-01 1.48645741e+00 1.03831382e+00 1.07162896e+00
  1.81144072e+00]
 [1.07906299e+00 7.48336804e-01 9.43921650e-02 1.63640638e+00
  8.38376164e-01]
 [6.08158564e-01 1.06759312e+00 1.08980045e+00 4.12721963e-01
  1.53592025e-01]
 [2.90688635e+00 1.06759312e+00 1.69047786e+00 3.34415413e-16
  5.10870706e-01]
 [1.02996395e+00 2.76348267e+00 1.91358662e+00 1.35401767e+00
  6.20511783e-01]
 [6.08158564e-01 5.28688459e-01 1.24426036e+00 1.18748074e+00
  1.44140209e-01]
 [4.67556767e-01 1.48645741e+00 1.22709815e+00 3.34415413e-16
  2.13138472e-01]
 [2.35452215e-01 4.29080489e-01 1.69047786e+00 3.34415413e-16
  1.07656195e+00]
 [8.89362157e-01 5.28688459e-01 1.11554377e-01 1.44814724e+00
  2.72684919e-01]
 [3.76054011e-01 8.47944775e-01 7.29394002e-01 7.16832883e-01
  4.41872442e-01]
 [4.57513782e-02 1.48645741e+00 6.26420731e-01 7.16832883e-01
  1.03733691e+00]
 [4.57513782e-02 8.47944775e-01 3.00338707e-01 5.06851534e-01
  8.58697570e-01]
 [7.97859400e-01 5.28688459e-01 2.14527648e-01 6.95110675e-01
  1.83365249e-01]
 [3.26954971e-01 2.09432143e-01 1.70764008e+00 1.07162896e+00
  1.87098717e+00]
 [9.48504182e-02 1.06759312e+00 7.63718426e-01 2.24462822e-01
  1.07656195e+00]
 [1.73297294e+00 1.16720109e+00 1.43304469e+00 3.34415413e-16
  7.69377900e-01]
 [1.02996395e+00 1.48645741e+00 1.03831382e+00 5.79258896e-02
  6.80058230e-01]
 [9.48504182e-02 1.06759312e+00 1.07263824e+00 1.63640638e+00
  2.44613023e+00]
 [1.31116755e+00 8.47944775e-01 1.02115160e+00 1.07162896e+00
  1.58270675e+00]
 [1.17056575e+00 2.09432143e-01 1.45878800e-01 1.46986945e+00
  1.83365249e-01]
 [1.50086838e+00 1.09824173e-01 1.97365436e-01 1.07162896e+00
  7.19283270e-01]
 [4.67556767e-01 2.44422635e+00 8.83853909e-01 9.99221595e-01
  9.48017240e-01]
 [2.20387736e+00 1.06759312e+00 2.66014283e-01 9.77499386e-01
  4.51324259e-01]
 [4.67556767e-01 4.29080489e-01 1.65615344e+00 5.06851534e-01
  1.39461559e+00]
 [9.38461197e-01 4.29080489e-01 1.97365436e-01 1.18748074e+00
  2.63233102e-01]
 [7.48760360e-01 1.09824173e-01 1.39872026e+00 6.22703313e-01
  8.88470793e-01]
 [8.89362157e-01 1.06759312e+00 9.43921650e-02 8.10962454e-01
  2.50473149e-02]
 [1.86353175e-01 1.80571372e+00 2.17101980e+00 1.46986945e+00
  1.54348171e+00]
 [2.48508096e+00 1.06759312e+00 1.19277372e+00 3.40314601e-01
  1.09688336e+00]
 [8.89362157e-01 2.09432143e-01 7.29394002e-01 1.30333252e-01
  4.12099219e-01]
 [6.08158564e-01 7.48336804e-01 1.17561151e+00 3.34415413e-16
  5.31192113e-01]
 [5.16655807e-01 2.09432143e-01 1.97365436e-01 6.95110675e-01
  7.49056493e-01]
 [1.45176934e+00 5.28688459e-01 4.29055296e-02 4.12721963e-01
  5.10870706e-01]
 [3.76054011e-01 1.09824173e-01 2.48852071e-01 2.46185031e-01
  5.70417153e-01]
 [9.48504182e-02 4.29080489e-01 1.02115160e+00 8.83369816e-01
  1.19565484e+00]
 [1.86353175e-01 4.35976425e+00 1.14128709e+00 3.40314601e-01
  1.30529592e+00]
 [1.59237114e+00 8.47944775e-01 9.69664968e-01 3.34415413e-16
  1.30529592e+00]
 [3.76054011e-01 5.28688459e-01 6.77907367e-01 1.52055460e-01
  6.42723553e-02]
 [2.35452215e-01 1.16720109e+00 1.12412487e+00 3.34415413e-16
  3.22779549e-01]
 [4.67556767e-01 1.16720109e+00 4.71960825e-01 6.95110675e-01
  9.18244017e-01]
 [9.38461197e-01 4.29080489e-01 2.48852071e-01 3.63484957e+00
  5.70417153e-01]
 [3.26954971e-01 2.09432143e-01 4.54798613e-01 1.44814724e+00
  1.83365249e-01]
 [1.07906299e+00 5.28688459e-01 1.96507325e+00 5.28573742e-01
  1.48393526e+00]
 [1.59237114e+00 2.09432143e-01 2.27399307e+00 9.05092025e-01
  2.25803907e+00]
 [1.21966479e+00 7.48336804e-01 5.57771884e-01 4.12721963e-01
  5.10870706e-01]
 [3.76054011e-01 7.48336804e-01 1.50169353e+00 2.46185031e-01
  1.14366985e-01]
 [1.21966479e+00 4.29080489e-01 8.66691697e-01 1.44814724e+00
  1.31474774e+00]
 [6.08158564e-01 1.80571372e+00 6.77907367e-01 6.95110675e-01
  1.57325493e+00]
 [4.67556767e-01 1.48645741e+00 8.58110591e-03 6.22703313e-01
  6.00190376e-01]
 [1.78207198e+00 1.06759312e+00 2.66014283e-01 7.89240245e-01
  6.29963600e-01]
 [5.16655807e-01 1.06759312e+00 1.02115160e+00 1.25988810e+00
  1.22542807e+00]
 [1.86353175e-01 4.29080489e-01 4.71960825e-01 1.07162896e+00
  1.23818802e-01]
 [5.16655807e-01 4.29080489e-01 8.83853909e-01 2.46185031e-01
  8.28924347e-01]
 [4.67556767e-01 1.16720109e+00 1.97365436e-01 4.34444172e-01
  7.49056493e-01]
 [9.38461197e-01 1.38684944e+00 2.14527648e-01 8.83369816e-01
  4.21551036e-01]
 [7.97859400e-01 5.28688459e-01 2.47993961e+00 7.16832883e-01
  1.54348171e+00]
 [6.08158564e-01 1.06759312e+00 9.43921650e-02 4.12721963e-01
  5.70417153e-01]
 [1.07906299e+00 2.09432143e-01 3.51825342e-01 3.18592393e-01
  1.37429418e+00]
 [6.57257604e-01 1.38684944e+00 3.17500919e-01 4.34444172e-01
  5.40643930e-01]
 [1.50086838e+00 2.09432143e-01 6.00677414e-02 5.06851534e-01
  2.13138472e-01]
 [3.76054011e-01 7.48336804e-01 2.48852071e-01 4.12721963e-01
  1.83365249e-01]
 [4.67556767e-01 4.29080489e-01 1.45878800e-01 3.62036810e-02
  1.40406741e+00]
 [3.26954971e-01 2.09432143e-01 8.32367273e-01 2.88181301e+00
  1.53592025e-01]
 [3.76054011e-01 2.09432143e-01 8.66691697e-01 7.16832883e-01
  1.67202642e+00]
 [7.97859400e-01 1.38684944e+00 6.60745155e-01 8.83369816e-01
  1.53592025e-01]
 [3.26954971e-01 8.47944775e-01 7.12231791e-01 6.00981104e-01
  1.70179964e+00]
 [7.48760360e-01 4.29080489e-01 1.19277372e+00 2.46185031e-01
  1.73913432e-01]
 [4.57513782e-02 4.29080489e-01 4.29055296e-02 3.16420172e+00
  1.73913432e-01]
 [1.31116755e+00 4.29080489e-01 2.14527648e-01 4.12721963e-01
  6.00190376e-01]
 [1.31116755e+00 1.06759312e+00 2.48852071e-01 2.46185031e-01
  1.19565484e+00]
 [9.48504182e-02 4.29080489e-01 7.29394002e-01 1.52055460e-01
  7.39604676e-01]
 [1.86353175e-01 4.29080489e-01 2.14527648e-01 1.18748074e+00
  5.48205383e-02]
 [1.36026659e+00 1.06759312e+00 1.11554377e-01 3.18592393e-01
  5.01418889e-01]
 [4.67556767e-01 2.09432143e-01 8.83853909e-01 7.16832883e-01
  1.21597625e+00]
 [1.31116755e+00 1.09824173e-01 4.71960825e-01 5.28573742e-01
  4.71645666e-01]
 [4.57513782e-02 1.06759312e+00 3.68987554e-01 4.34444172e-01
  2.63233102e-01]
 [1.64147018e+00 8.47944775e-01 4.20474190e-01 1.28161031e+00
  1.03733691e+00]
 [9.48504182e-02 8.47944775e-01 1.34723363e+00 8.10962454e-01
  8.88470793e-01]
 [5.16655807e-01 1.06759312e+00 3.00338707e-01 1.16575853e+00
  2.13138472e-01]
 [2.34447916e+00 4.29080489e-01 7.63718426e-01 1.35401767e+00
  7.19283270e-01]]
(122, 5)

In [21]:
data2.to_csv('Australia Open 2013_2.csv', sep=';')

In [22]:
#normalization untuk data tanpa missing value
from sklearn.preprocessing import normalize
norm = normalize(data,norm = 'l2')
norm = pd.DataFrame(norm)
norm.tail()

            0         1         2         3         4
121  0.423234  0.006938  0.284469  0.187333  0.839529
122  0.421136  0.040383  0.242297  0.207683  0.848041
123  0.366498  0.041379  0.354676  0.183249  0.839399
124  0.511716  0.007873  0.220431  0.078726  0.826618
125  0.653137  0.025121  0.159098  0.066988  0.736873

In [23]:
#transformasi untuk data tanpa missing value
tsig1=(1-2.718281828**(-norm))/(1+2.718281828**(-norm))
tsig1=pd.DataFrame(tsig1)
tsig1.tail()

            0         1         2         3         4
121  0.208514  0.003469  0.141283  0.093394  0.396732
122  0.207510  0.020189  0.120559  0.103470  0.400312
123  0.181225  0.020686  0.175502  0.091369  0.396677
124  0.250417  0.003936  0.109772  0.039342  0.391279
125  0.315434  0.012560  0.079381  0.033482  0.352623

In [24]:
tsig1.to_csv('Australia Open 2013_3.csv', sep=';')

In [27]:
#normalization untuk data tanpa missing value dan outlier
from sklearn.preprocessing import normalize
norm2= normalize(data2,norm= 'l2')
norm2= pd.DataFrame(norm2)
norm2.tail()

            0         1         2         3         4
117  0.423234  0.006938  0.284469  0.187333  0.839529
118  0.421136  0.040383  0.242297  0.207683  0.848041
119  0.366498  0.041379  0.354676  0.183249  0.839399
120  0.511716  0.007873  0.220431  0.078726  0.826618
121  0.653137  0.025121  0.159098  0.066988  0.736873

In [28]:
#transformasi untuk data tanpa missing value
tsig2=(1-2.718281828**(-norm2))/(1+2.718281828**(-norm2))
tsig2=pd.DataFrame(tsig2)
tsig2.tail()

            0         1         2         3         4
117  0.208514  0.003469  0.141283  0.093394  0.396732
118  0.207510  0.020189  0.120559  0.103470  0.400312
119  0.181225  0.020686  0.175502  0.091369  0.396677
120  0.250417  0.003936  0.109772  0.039342  0.391279
121  0.315434  0.012560  0.079381  0.033482  0.352623

In [29]:
tsig2.to_csv('Australia Open 2013_4.csv', sep=';')